// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Simon Wright

package apivectors

import (
	"context"
	"fmt"

	"github.com/trigstation/trigstationd/internal/query"
	"github.com/trigstation/trigstationd/internal/signal"
)

// Generate builds the complete API vector file. It is deterministic: the same
// inputs always produce byte-identical output.
func Generate(ctx context.Context) (*File, error) {
	g := &generator{ctx: ctx, coverage: map[string][]string{}}

	if err := g.buildInitialState(); err != nil {
		return nil, err
	}
	if err := checkDistinctIdentifiers(g.initial); err != nil {
		return nil, err
	}
	for _, r := range g.initial {
		if r.id != "record-adversarial-formatting" {
			continue
		}
		if err := checkAdversarialRecord(r.body); err != nil {
			return nil, err
		}
	}

	g.buildMetaFixtures()
	if err := g.buildRecordFixtures(); err != nil {
		return nil, err
	}
	if err := g.buildLookupFixtures(); err != nil {
		return nil, err
	}
	g.buildSignalFixtures()
	g.buildCORSFixtures()

	return g.file()
}

func (g *generator) file() (*File, error) {
	coverage := make([]CoverageRow, 0, len(coverageRows))
	for _, row := range coverageRows {
		ids := g.coverage[row.key]
		if len(ids) == 0 {
			return nil, fmt.Errorf("apivectors: no fixture covers %s (%s)", row.key, row.row)
		}
		coverage = append(coverage, CoverageRow{
			Table:    row.table,
			Row:      row.row,
			Status:   row.status,
			Fixtures: ids,
		})
	}

	records := make([]InitialRecord, 0, len(g.initial))
	for _, r := range g.initial {
		records = append(records, InitialRecord{
			ID:               r.id,
			Note:             r.note,
			LookupID:         lookupIDOf(r),
			LoadedAt:         Now,
			ExpiresAt:        r.expiresAt,
			LoadExpectStatus: 204,
			Envelope:         Body{Encoding: BodyUTF8, Value: r.body},
		})
	}

	return &File{
		Comment: "Trigstation directory service — protocol v1 API conformance vectors for DIRECTORY-SPEC.md §5. " +
			"Generated by cmd/gen-api-vectors; regenerating must reproduce this file byte for byte.",
		Warning: []string{
			"TEST ONLY. Every key here is derived from a counting sequence hashed with a published domain " +
				"string. They are reproducible by anyone and secret to nobody.",
			"Every expectation is evaluated against the fixed clock in `now`, never against wall time. A " +
				"harness that uses its own clock will see records expire and fixtures fail for reasons that " +
				"have nothing to do with conformance.",
			"Each fixture is driven against a freshly built instance holding the declared initial state. " +
				"Fixtures whose `mutates_state` is true change what the instance holds, so a harness that " +
				"cannot reset between fixtures must run those last and cannot claim order independence.",
			"pow_bits is 8 here, not the default 20. §6.1 makes it an instance parameter, and verification " +
				"costs one SHA-256 at any difficulty — only solving is exponential. The shipped default is " +
				"exercised by testdata/vectors.json.",
		},
		Spec:        "DIRECTORY-SPEC.md protocol version 1 (draft), §5.1–§5.5",
		GeneratedBy: "cmd/gen-api-vectors",
		Now:         Now,
		Encoding:    encodingNotes(),
		Harness: Harness{
			Note: []string{
				"Build an instance from the named entry in `instances`, load `initial_state` into it, run " +
					"any `prior_requests`, then issue `request` and compare the response against `expect`.",
				"Load the records by issuing the PUT given in each initial_state.records[] entry, with the " +
					"instance's clock reading `loaded_at`; each returns 204. A directory that loads its " +
					"state some other way MUST store the envelope bytes verbatim.",
				"Load the signal channels by issuing a POST of each blob to its channel_id with the " +
					"instance's clock reading `posted_at`; each returns 204. One channel is loaded in the " +
					"past so that its blob has expired by `now`.",
				"Reset the instance between fixtures. Every fixture is then order-independent: none " +
					"depends on a state another leaves behind.",
			},
			ResetBetweenFixtures: true,
			OrderIndependent:     true,
		},
		Instances:    instances(),
		InitialState: InitialState{Note: initialStateNotes(), Records: records, SignalChannels: g.channels},
		ResponseInvariants: ResponseInvariants{
			Note: []string{
				"§5.5 requires Access-Control-Allow-Origin: * on every /v1/ response — including the ones " +
					"no handler produces, such as a 404 for an unregistered path under /v1/ and a 405 for a " +
					"method that is not one of the four. A browser cannot read an error it is not allowed to see.",
				"A wildcard origin is safe here in a way it is not for most services, because the API " +
					"carries no ambient authority: no cookies, no credentials, no session, and every write " +
					"is authorised by a signature in the body.",
				"Access-Control-Allow-Credentials MUST NOT be sent, from anywhere, on any response.",
				"These are asserted on every fixture in this file rather than restated on each.",
			},
			AppliesTo:     "every response to a request whose path begins with /v1/",
			Headers:       map[string]string{"Access-Control-Allow-Origin": "*"},
			HeadersAbsent: []string{"Access-Control-Allow-Credentials"},
		},
		Coverage: coverage,
		Fixtures: g.fixtures,
	}, nil
}

func lookupIDOf(r storedRecord) string {
	return encodeLookupID(r.publisher.lookupID)
}

func initialStateNotes() []string {
	return []string{
		fmt.Sprintf("%d records and %d signal channels. The record count is exactly 2 × k_min, which is "+
			"the smallest instance on which §5.3's cap — max(0, floor(log2(record_count / k_min))) — is "+
			"greater than zero, and therefore the smallest on which a masked prefix query can be shown to "+
			"work at all.", InitialRecordCount, 2),
		"Every identifier here begins with a 1 bit. That is deliberate: at a cap of 1 bit the only " +
			"queries available are bits = 0 and bits = 1, and a table whose identifiers all share their " +
			"first bit answers the two halves of that query with the whole table and with nothing — which " +
			"is what makes both the matching case and §5.3's empty-result shape observable on an instance " +
			"small enough to ship as a fixture.",
		"One record is stored with formatting a re-serialising directory would destroy. Every response " +
			"that contains it is byte-exact only if the directory reproduced the bytes it received.",
		"Records are given as the exact bytes a publisher sent, and §5.2 requires those bytes to be what " +
			"§5.3 returns.",
	}
}

func instances() []Instance {
	base := Instance{
		MaxTTL:                  MaxTTL,
		MaxRecordBytes:          MaxRecordBytes,
		PoWBits:                 PoWBits,
		SkewGrace:               SkewGrace,
		Signal:                  true,
		MaxSignalBlobBytes:      signal.MaxBlobBytes,
		SignalTTL:               SignalTTL,
		SignalPollWindowMaximum: SignalPollWindowMaximum,
		KMin:                    query.KMin,
		SourceURL:               SourceURL,
		RateLimits: RateLimits{
			PutRecord:     generousLimit,
			GetRecord:     generousLimit,
			Signal:        generousLimit,
			WindowSeconds: limitWindowSecs,
		},
		LoadInitialRecords:  true,
		LoadInitialChannels: true,
	}

	def := base
	def.Name = InstanceDefault
	def.Note = []string{
		"A conforming instance holding the declared initial state, with allowances high enough that no " +
			"fixture reaches them.",
		"signal_poll_window_maximum is the §5.4 ceiling, not a setting: a directory MUST NOT hold a " +
			"long-poll open for longer, and SHOULD hold it for the full 30 seconds for real clients. A " +
			"conformance harness MAY shorten it, because the GET-with-no-blob fixture asserts the status " +
			"and not the duration.",
	}

	disabled := base
	disabled.Name = InstanceSignalDisabled
	disabled.Signal = false
	disabled.LoadInitialChannels = false
	disabled.Note = []string{
		"The same instance with signal channels off, which is the only configuration in which §5.4 " +
			"answers 404. It holds the same records, so its GET /v1/meta reports the same record_count.",
	}

	draining := base
	draining.Name = InstanceDraining
	draining.Draining = true
	draining.Note = []string{
		"The same instance after it has begun a graceful shutdown: still listening, no longer able to " +
			"broker a rendezvous. §5.4 binds this to 429 for either method — the same code as at capacity, " +
			"because the client's correct response is the same.",
		"Draining releases every in-flight long-poll and drops every stored blob, so the pre-loaded " +
			"channels are gone by the time a fixture runs against this instance.",
	}

	limited := base
	limited.Name = InstanceLimitsOfOne
	limited.RateLimits = RateLimits{
		PutRecord:     exhaustibleLimit,
		GetRecord:     exhaustibleLimit,
		Signal:        exhaustibleLimit,
		WindowSeconds: limitWindowSecs,
	}
	limited.LoadInitialRecords = false
	limited.LoadInitialChannels = false
	limited.Note = []string{
		"An instance whose per-class allowance is one request per window, and which holds no initial " +
			"state — loading it would spend the allowance the fixtures exist to spend deliberately.",
		"The rate-limit rows of §5.2 and §5.4 cannot be expressed by a single request, so they are " +
			"expressed as this instance plus a prior request that spends the class's allowance.",
		"§6.4 counts the three classes independently, and the fixtures rely on it: a prior GET spends " +
			"nothing a POST needs.",
	}

	return []Instance{def, disabled, draining, limited}
}

func encodingNotes() Encoding {
	return Encoding{
		Note: "How a value in this file becomes bytes on the wire. Nothing here assumes a language, a " +
			"routing library or a JSON implementation.",
		BinaryValues: "Binary values outside request and response bodies — channel identifiers, lookup " +
			"identifiers — are unpadded base64url, RFC 4648 §5, canonically encoded per §4.4. No '=' is " +
			"ever emitted.",
		Bodies: "Every request and response body is an object carrying its own encoding, so that a " +
			"binary body and a JSON body are read the same way. A body that is meant to be absent says so " +
			"explicitly rather than being omitted.",
		BodyEncodings: []NamedNote{
			{BodyEmpty, "No body at all. Send nothing; expect zero bytes."},
			{BodyUTF8, "`value` is the body, character for character, encoded as UTF-8. Used for JSON " +
				"bodies so that whitespace and member order are visible to a reader."},
			{BodyBase64URL, "`value` decodes as unpadded base64url to the body bytes. Used where the body " +
				"is binary or contains bytes no text encoding should be trusted with."},
			{BodyRepeatedByte, "The single byte `byte` (0–255, absent means 0) repeated `length` times. " +
				"Used for the payload-limit fixtures, where writing 64 KiB of literal data into this file " +
				"would obscure everything around it."},
		},
		Comparisons: []NamedNote{
			{CompareEmpty, "The response must carry no body bytes."},
			{CompareExactBytes, "The response body must equal the expected bytes exactly."},
			{CompareJSONObject, "The response must be a JSON object equal to the expected one. Member " +
				"order is not significant in JSON and is not compared."},
			{CompareRecordsArray, "The response must be a JSON object whose only member is `records`, an " +
				"array whose elements are the expected elements as a multiset — each compared as **bytes**, " +
				"not as parsed values. §5.2 requires the bytes returned to be the bytes received, and a " +
				"comparison of parsed values is exactly the comparison that passes with a re-serialising " +
				"directory. The order of `records` is not significant (§5.3); the expected body is written " +
				"in the RECOMMENDED order, ascending lookup_id."},
		},
		Headers: "Request headers are sent as given. Header names are case-insensitive per RFC 9110. " +
			"`expect.headers` must match exactly, `expect.header_tokens` names headers whose " +
			"comma-separated value must contain every token listed — order, spacing and additional tokens " +
			"are not significant — and `expect.headers_absent` must not appear at all.",
		Query: "`query` is the raw query string without a leading '?', to be appended to `path` " +
			"unmodified. It is raw rather than a map because §5.3 requires a repeated parameter to be " +
			"rejected rather than resolved, and a map cannot express one.",
		Conditions: []NamedNote{
			{condAccepted, "§5.2 — the publish was accepted and stored."},
			{condRateLimited, "§5.2 and §5.4 — the source's allowance for this class is spent."},
			{condTooLarge, "§5.2 — the received body exceeds max_record_bytes, measured as transmitted."},
			{condMalformed, "§5.2 — not well-formed JSON, a required member absent or null, a duplicate " +
				"member, a value that is not valid unpadded canonical base64url, or a fixed-width field of " +
				"the wrong decoded length."},
			{condBadVersion, "§5.2 — v is not 1."},
			{condTTLTooLong, "§5.2 — expires_at exceeds now + max_ttl, after the skew grace."},
			{condLookupMismatch, "§5.2 — lookup_id is not SHA-256(wk_pub)."},
			{condPoWInsufficient, "§5.2 — pow does not satisfy pow_bits."},
			{condSigInvalid, "§5.2 — sig does not verify under wk_pub."},
			{condExpired, "§5.2 — expires_at is not strictly greater than the directory's current time."},
			{condNotNewer, "§5.2 — expires_at is not strictly greater than that of an unexpired stored " +
				"record under the same lookup_id."},
			{condStored, "§5.4 — the blob was stored."},
			{condDelivered, "§5.4 — a blob was delivered."},
			{condEmpty, "§5.4 — the long-poll window elapsed with no blob."},
			{condBadChannel, "§5.4 — channel_id is not exactly 32 bytes of unpadded base64url."},
			{condConflict, "§5.4 — the channel already holds an unexpired blob."},
			{condSignalLarge, "§5.4 — the body exceeds the §4.3 signal channel payload limit."},
			{condDisabled, "§5.4 — the instance advertises \"signal\": false."},
		},
		Tables: []TableOrder{
			{
				Table:     "§5.2",
				Normative: true,
				Note: "The conditions MUST be evaluated in this order and the directory MUST return the " +
					"code of the first that fails. Without a fixed order a request violating two conditions " +
					"receives a different code from different directories, and a publisher's retry logic — " +
					"driven entirely by the code — diverges accordingly. The order is also cheapest-first: " +
					"the two SHA-256 checks precede the Ed25519 verification, which costs roughly two orders " +
					"of magnitude more.",
				Conditions: recordConditionOrder,
			},
			{
				Table:     "§5.3",
				Normative: false,
				Note: "§5.3 binds every rejection to 400 and gives no evaluation order, so the choice " +
					"between two reasons can never be observed on the wire.",
				Conditions: []string{},
			},
			{
				Table:     "§5.4",
				Normative: false,
				Note: "The conditions of the §5.4 table are disjoint, so their order carries no meaning. " +
					"The one exception is not an ordering: an instance that is disabled answers 404 without " +
					"regard to anything else about the request.",
				Conditions: []string{},
			},
		},
	}
}
